/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MakerContractInterface extends ethers.utils.Interface {
  functions: {
    "addAdmin(address)": FunctionFragment;
    "addMaker(address)": FunctionFragment;
    "getAdmin(uint256)": FunctionFragment;
    "getAdminCount()": FunctionFragment;
    "getMakerLogoUri()": FunctionFragment;
    "getMakerName()": FunctionFragment;
    "getMakers()": FunctionFragment;
    "getMakersCount()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addAdmin", values: [string]): string;
  encodeFunctionData(functionFragment: "addMaker", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMakerLogoUri",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMakerName",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getMakers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMakersCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addMaker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdminCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMakerLogoUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMakerName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMakers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMakersCount",
    data: BytesLike
  ): Result;

  events: {};
}

export class MakerContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MakerContractInterface;

  functions: {
    addAdmin(
      _newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addMaker(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAdmin(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAdminCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMakerLogoUri(overrides?: CallOverrides): Promise<[string]>;

    getMakerName(overrides?: CallOverrides): Promise<[string]>;

    getMakers(overrides?: CallOverrides): Promise<[string[]]>;

    getMakersCount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addAdmin(
    _newAdmin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addMaker(
    _address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAdmin(_index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getAdminCount(overrides?: CallOverrides): Promise<BigNumber>;

  getMakerLogoUri(overrides?: CallOverrides): Promise<string>;

  getMakerName(overrides?: CallOverrides): Promise<string>;

  getMakers(overrides?: CallOverrides): Promise<string[]>;

  getMakersCount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addAdmin(_newAdmin: string, overrides?: CallOverrides): Promise<void>;

    addMaker(_address: string, overrides?: CallOverrides): Promise<void>;

    getAdmin(_index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getAdminCount(overrides?: CallOverrides): Promise<BigNumber>;

    getMakerLogoUri(overrides?: CallOverrides): Promise<string>;

    getMakerName(overrides?: CallOverrides): Promise<string>;

    getMakers(overrides?: CallOverrides): Promise<string[]>;

    getMakersCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addAdmin(
      _newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addMaker(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAdmin(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAdminCount(overrides?: CallOverrides): Promise<BigNumber>;

    getMakerLogoUri(overrides?: CallOverrides): Promise<BigNumber>;

    getMakerName(overrides?: CallOverrides): Promise<BigNumber>;

    getMakers(overrides?: CallOverrides): Promise<BigNumber>;

    getMakersCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addAdmin(
      _newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addMaker(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAdmin(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAdminCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMakerLogoUri(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMakerName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMakers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMakersCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
