name: pull-request
on:
  pull_request:
    branches: [ main ]
env:
  REACT_APP_COVALENT_API_KEY: ${{ secrets.REACT_APP_COVALENT_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: cd nft-mrkt-frontend && npm ci
      - name: Run tests
        run: cd nft-mrkt-frontend && CI=true npm test

